### ISSUE TITLE
add a list of 101 links to the code of conduct page

### ISSUE THREAD

**Issue by adacable** [computeranonymous/computer#101]
http://superopinionated.com/101-a-tron/ has been suggested. 

So when people come asking about trans stuff, we can link them there. 

They should be on computer website so it seems official ish

**Comment by janepipistrelle** [comment]
The first two links you posted here need to be in, I think: https://github.com/computeranonymous/computer/issues/67

And I think this is good because, brevity: http://theangryblackwoman.com/2009/10/01/the-dos-and-donts-of-being-a-good-ally/

Edit: I missed that 101-a-tron also contains a huge list of links, including the trans101 you linked to. I vote for using it, rather than re-inventing the wheel.
