### ISSUE TITLE
tef is going to burn out if we let him

### ISSUE THREAD

**Issue by DRMacIver** [computeranonymous/computer#110]
Proposed solution:
- Ask tef what is taking up most of his time
- Call for volunteers to assist with individual tasks from that. Ideally several per task
- Buy him drinks on Thursday's meetup and talk to him about what is most likely to cause him to burn out
  - See what we can do to fix anything that emerges from the previous step

Alternative solutions welcome.

**Comment by tef** [comment]
Note:
- I've delegated channel administration and merge handling as much as possible, but will continue to do so in future
- @ntlk is helping run the WhyComputer twitter, but we should be aware that letting one person take on things isn't a perfect solution
- Much of my energy is sapped for reasons outside of computer, it is just dealing and responding to incidents is very time and effort consuming. 
- Most of the meetups run themselves, so I'd love to get someone else to plan the next one, after talking to people on thursday.

Frankly, this weekend aside, it's been very quiet for the last 48 hours by comparison and i'd like to keep it that way.

**Comment by tef** [comment]
Most of the problem comes from the handling of incidents. Other people can jump in on perceived hostility and it becomes very very quick to burn bridges.  I've had some people jump to my rescue over my fuckups, but in effect compound them by wanting to save face. I'm happy to admit I fuck up, telling people "I'm a nice guy" doesn't help.

Another problem is that dealing with people who are being kicked or banned is that attention from the larger group can and will backfire. If someone is refusing to listen or to learn, I would rather ignore them, although cheap jokes are fun, they really only encourage the divide. I'm a big filthy pacifist and I do like to think my weapon of choice is education and patience, and I know that is a considerable amount to ask from other people.

I strongly believe in a matter of fact approach to bannings/incident handling: This is what happened, this is the actions you have done, and this is why we've gotten rid of you. Dealing with these things in a dull, boring and straight forward manner should hopefully discourage them from becoming noisier and louder. We shouldn't give them any more attention than they deserve.

I don't have much experience with dealing with these specific groups, but I have been moderating forums and irc channels for almost a decade, and knowing which fights to pick has kept me somewhat sane. I'd like to see any guidance, policy and documentation for people on both sides of the ban, in our usual casual and short style.

This is where an FAQ would be handy - i.e what is transphobia, etc.

**Comment by tef** [comment]
I guess i'm saying that shunning and ignoring those who don't want to play nicely is a powerful tactic, and that calling  people shitheads over twitter is not something we should actively encourage. The more we engage and respond to them, the more they become entrenched and shouty. 

I'd love to have someone correct me on this who has more experience. Hjalp

**Comment by ntlk** [comment]
It's important that our FAQ doesn't turn into "here all all the ills of the world, and here a detailed guides on every way you might be behaving in a harmful way". It's not our job to educate people how to be decent members of society.

**Comment by AgentAntelope** [comment]
@ntlk perhaps the way to avoid that is to only add questions that are actually asked frequently.

**Comment by tef** [comment]
:+1:

For example, ashedryden's attempts are wonderful. https://twitter.com/ashedryden/status/385048174559125504  No jokes, no attacks, just information, and disengages when they realise it's a lost cause.

So maybe we should just all be like ashe.

**Comment by ntlk** [comment]
+1 to "we should all be like @ashedryden"

On 2 October 2013 at 10:10:31, tef (notifications@github.com) wrote:

For example, ashedryden's attempts are wonderful. https://twitter.com/ashedryden/status/385048174559125504 No jokes, no attacks, just information, and disengages when they realise it's a lost cause.

So maybe we should just all be like ashe.

**Comment by ntlk** [comment]
Although I don't know where to find patience, I tend to just roll my eyes, disengage, and never come back

**Comment by adacable** [comment]
While I agree that all the ills in the world would be a bad idea: It really is helpfull not to have to explain everything to people who come in expecting explanation. The binarist dude in the de channel is a perfect example- #101 (I'll ad a PR for that later) would allow us to say "go read" (which we did, but "computer-official" sheen would give us more credence if we kb/etc people for this. )

Tef burnout: It sounds like this is easing up. #76 should help, as suggested by tef, and should alos mean we don't need it to be always him handling incidents.

Also, hugs dude. (how is there no :hugs: ?

**Comment by ntlk** [comment]
Wait, there's no :hugs:??? WHAT IS WRONG WITH THE WORLD

**Comment by igalic** [comment]
wow! That twitter thread from @ashedryden was absolutely wonderful!!

**Comment by ntlk** [comment]
Yeah, @ashedryden is amazing <3 <3 <3

**Comment by igalic** [comment]
Also, we should probably open an issue with @github to support :hugs:

**Comment by adacable** [comment]
@igalic I think we need to open it with whoever runs emoji. Is there an emojii consortium?

**Comment by ntlk** [comment]
Gihub has a lot of custom emojis, like :shipit: (shipit)

On 2 October 2013 at 15:07:56, Thomas Walpole (notifications@github.com) wrote:

@igalic I think we need to open it with whoever runs emoji. Is there an emojii consortium?

**Comment by adacable** [comment]
Hmmm... :hugs: should be universal though?

**Comment by adacable** [comment]
https://github.com/github/gemoji Someone get me a :hugs: image and I'll make a pull request.

**Comment by ashedryden** [comment]
I'm not crying DONT LOOK AT ME

**Comment by gearmonkey** [comment]
this one is pretty good http://thenounproject.com/noun/hug/#icon-No14618
though it's CC-BY, not sure if it's compatible with the licensing for gemoji...

**Comment by adacable** [comment]
@gearmonkey :+1: checking licencing

**Comment by gearmonkey** [comment]
(also, I love The Noun Project)

**Comment by adacable** [comment]
Looks like CC-BY should be compatible if I stick it in the licence. pull request coming soon.

**Comment by adacable** [comment]
https://github.com/github/gemoji/pull/36

**Comment by gearmonkey** [comment]
:+1:

**Comment by tef** [comment]
:+1:

**Comment by adacable** [comment]
Stick the :+1: on the issue? We might even get it merged.

**Comment by catamorphism** [comment]
As far as informative links in the FAQ about topics such as cissexism goes, https://github.com/freenode-feminists/wiki/wiki/List-of-Educational-Resources has quite a few good educational links (though they should be checked before inclusion, as some have bitrotted in the meantime :-( )

**Comment by ntlk** [comment]
Okay, I think @tef will be fine now, closing this
