### ISSUE TITLE
more specific statement of inclusivity in code of conduct

### ISSUE THREAD

**Issue by janepipistrelle** [computeranonymous/computer#19]
I'm happy to draft a sentence or two if others feel it's needed.

I kind of like the idea of adding something along the lines of what Nine Worlds sci-fi con said: "we want to prioritise the voices of people who are often spoken over or erased in geek spaces, and make Nine Worlds as accessible as we can to people from all racial backgrounds." (maybe with less emphasis on race and just "of all backgrounds").

Their full anti-harassment policy: https://nineworlds.co.uk/anti-harassment-policy

(also fwiw I'm doing a bit of research on creating inclusive spaces for something else, so am happy to contribute).

**Comment by DRMacIver** [comment]
I'm extremely pro doing this, and I imagine most of us are. We struggled in IRC over the phrasing of our inclusivity statements and I would definitely like them to be better.

The 9W anti-harassment policy is I believe based on the geek feminism one we reference, but I agree it was really good and should be emulated.

**Comment by russss** [comment]
I'm very much in favour of not writing a massive diversity statement for what is in essence a few people meeting in the pub (more generally I'm in favour of making these kind of things concise and pithy, because I think the tendency is to make them all-encompassing and wordy).

As a start, how about we revise the existing inclusivity rule to something like:
- We want to be inclusive: we'd love to see more people from backgrounds which are under-represented at most geeky meetups.
- Discriminatory or exclusionary behaviour is not appropriate.

**Comment by janepipistrelle** [comment]
David, I think it is, having done some more research. But agree with Russ that we should aim to be inclusive and brief-which is why I liked that one sentence from the Nine Worlds folk.

**Comment by tef** [comment]
I think we can put something in 'imposters welcome', rather than in the rules about welcoming people. We have something in the rules already about disciminatory and exclusionary behaviour.

Additonally, we have a complexity budget in the rules, we don't want to really have much more that what we have, so i'm more in favour of edits than additions.

**Comment by DRMacIver** [comment]
I like the idea of putting it in the imposters welcome section.

I think it's important to explicitly include some of the types of discrimination we don't allow (especially transphobia) because of the tendency of groups who describe themselves as inclusive to secretly mean "except for people like you" about some of these.

**Comment by ntlk** [comment]
@drcable said on IRC that we're not saying anything explicit about not being ableist

**Comment by adacable** [comment]
More specifically, while we cover ableist(ish) in the etc, we need to have some guides on venue location for people with disabilties and other groups(specifically those who have good reason to fear unlit streets, or those with little cash, for example. 

London may have this down(I trust it does) but others may not have grabbed these ones yet.

**Comment by janepipistrelle** [comment]
Totally agree. I know it's implicit, but  agree it should be explicitly stated also.

—

**Comment by tef** [comment]
Additonally, we need to be more explicit in the regional pages that there is a code of conduct

**Comment by AgentAntelope** [comment]
I think that we should explicitly say on the main page that all regional pages should link to the code of conduct.

**Comment by tef** [comment]
If they don't we won't list them. :-)

**Comment by tef** [comment]
In particular i'd like to add "uninvited physical contact, uninvited sexual attention" to the list of harassment.

**Comment by adacable** [comment]
Could we have "consented" instead of invited? Because brogrammers confusing "wearing what I want to" and "I want to be groped".

**Comment by drtortoise** [comment]
I agree with @drcable as I've met plenty of people who consider wearing particular clothing an invitation

**Comment by AgentAntelope** [comment]
I agree.

**Comment by janepipistrelle** [comment]
Agree with no non-consensual contact/comments; too many people don't get that.

**Comment by tef** [comment]
Right, things we need to add:
- Consent is important, and respecting people's boundaries. 
- Appearance is not an invitation for contact or attention.
- Respecting peoples identities, i.e misgendering.

Please open a PR if you can think of ways to either improve the language, or if you must, add a sentence. 

As stated, I am strongly against lists, and we have a complexity budget. We should seek to write more general ideals rather than enumerating specific actions (an endless task)

**Comment by adacable** [comment]
Have done a PR for consent based on your phrasing.

**Comment by tef** [comment]
All of these things are in I believe, closing bug
