### ISSUE TITLE
Edinburgh July meeting: when and why?

### ISSUE THREAD

**Issue by johnd** [computeranonymous/computer#317]
We're clear to get space at CodeBase (tech incubator in Argyle House - very central), but we need to pick a date pretty soon.

(Our communication with CodeBase:

https://www.irccloud.com/pastebin/uZMQo1EK

https://www.irccloud.com/pastebin/jm1kmVYp)

The 12th of July is a Saturday, so let's say that's out. I propose Thursday the 10th.

Also, we need discussion topics! Here's one: is tech really worse (more sexist, causes more depression, etc) than other industries, or are we just more aware of how crap we are?

Please suggest something better!

**Comment by leynos** [comment]
I'm up for the 10th July.

I think your proposed discussion topic is a good one. (Sorry).

**Comment by jarofgreen** [comment]
>    is tech really worse (more sexist, causes more depression, etc) than other industries, or are we just more aware of how crap we are?

Sorry to be pedantic, but the 2nd clause says we're better than other industries at noticing this stuff. I don't think that's necessarily right and certainly it's not a good basis to start from.

The 3rd possibility is that other industries are having the same conversations about bad working practices that we're having, we just don't notice because we aren't in them. Certainly other places are discussing this .... but if that's true, why aren't there any discussions across industries on this topic, and what can we do to facilitate this and ensure lessons learnt are transferred?

I do think this is a good topic to discuss tho. Tho I'm also seriously up for the language bashing topic to.

I can make the 10th.

I'm sending out the TM monthly email of events on Open Tech Calendar tomorrow (friday) afternoon, so if it can be put in before then that would be cool.

I really liked the B&B but Codebase is grand to. And we can retire to the Film House Cafe afterwards which does have some drink but also has tea, coffee, cake and food.

**Comment by johnd** [comment]
I think we can commit to July 10th at CodeBase. I'll talk to the CodeBase guys when I'm in tomorrow.

Didn't you do language bashing in June's meeting?

**Comment by jarofgreen** [comment]
I wasn't there, I did say in the issue when I proposed it I couldn't make it.

**Comment by johnd** [comment]
So, the 10th is, like, the one date that we can't have! I've asked for Wednesday the 9th, which I've just realised will clash with TechMeetup, so now I'm not sure what's best. Suggestions welcome, otherwise it'll default to Wednesday the 9th!

**Comment by jarofgreen** [comment]
Clashing with TM would be bad. I def couldn't make it. Can't it be in the B&B again this month then?

**Comment by johnd** [comment]
@jarofgreen: I'm quite keen to move use to CodeBase as I feel it's a lot more accessible to the community and easier to find. Also, I can go upstairs and ask them whereas I don't personally know the guy who gives us access to B&B.

If we'd rather default to B&B this month we need to get confirmation that we can use the space.

**Comment by leynos** [comment]
I'll ask pajh tomorrow if the room at the B&B is available.  The other option is to possibly postpone for a week?  I'll be away on the 17th, but I think for most people, Thursday is a good day, so that would be my suggestion if the room is unavailable on the 10th.

**Comment by johnd** [comment]
@leynos Any word on B&B? I'm not certain the space at CodeBase is available on the 17th, IIRC that was the other day it's booked for.

**Comment by leynos** [comment]
I haven't heard back yet, I'm afraid.

**Comment by leynos** [comment]
@johnd pajh at B+B says we're good for the 10th. He's booked us in.

**Comment by jarofgreen** [comment]
Oh for pete's sake, in a move which is highly embarrassing - especially given what I do - I've just noticed the 10th clashes with the Open Data Edinburgh Meetup http://opentechcalendar.co.uk/event/1423-open-data-edinburgh-meet-up-13 which I should go to. Very sorry ...

**Comment by flowerhack** [comment]
closing, since july is reasonably far past :)
