### ISSUE TITLE
Update group pages so that people listed are /primary points of contact/

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#57]
Rather than 'people who will turn up'

**Comment by seubert** [comment]
It was suggested on irc to use Twitter lists for maintaining a more fluid list of members. Possible, not ideal, IMO.

**Comment by tef** [comment]
For the moment i'm adding organizers to github and letting them go wild with merges. I want to split the repos #45, which might mitigate things too

**Comment by tef** [comment]
I've added a sentence to say people don't need to fork the repo to join

**Comment by decklin** [comment]
I thought that I should fork/add myself (because that's easy, right? privilege check :frowning:) to join and now I'm feeling a bit awkward about making other people think I'm an organizer: https://twitter.com/nynexrepublic/status/384855380582727680 (only insofar as that sounds important, and makes other people sound less important...)

Maybe this should be clarified more? It would feel more welcoming to me if there was an anyone-who-wants-to-show-up list (bearing in mind that not everyone wants to publicize this information and that is okay) in addition to a list of organizers/point-persons/whatever. 56964f848b just says you can add yourself _or_ talk to someone.

I am happy to merge other pulls, and participate in discussions about pinning down the time, but I don't have the capacity/time/spoons to help people create pulls (am I misguided to hope that this can be made accessible to everyone?) or initiate scheduling discussion until next week. I do very much want to help though.

(I haven't minded anyone talking at me on twitter or anything, even though my twitter is private -- it's actually really hard to expand your circle when you lock your account. And it's hard for me to expand my circle IRL. If I hadn't put my name there I might not have pushed myself to ask some local people.)

**Comment by tef** [comment]
We need to make the list more explicit, it's good to have people's names on, but it is also good to have a list of people who are willing to be contacted

**Comment by tef** [comment]
This seems good to close for now. Some of the wording has been improved.
