### ISSUE TITLE
Style and commit guide

### ISSUE THREAD

**Issue by tef** [computeranonymous/computer#88]
Guides for what commits will be accepted an be rejected
we're always open to changes
code of conduct is easiest to change in smaller steps than all at once

**Comment by tef** [comment]
we want to be explicit, not implicit
but we want to avoid special cases and lists where possible
we have a complexity budget
we want to avoid jargon and slang
we have to translate things so the less words the better

**Comment by tef** [comment]
we want to be conversational, not bureaucratic in tone

this is turning into the zen of computer anonymous

**Comment by adacable** [comment]
Proposal:Guide one should be "Safety of marginalized groups is the top priority."

Reasoning: If we're not safe for people, they won't attend and this is a problem. If the github, IRC and twitter are not safe for them, they can't raise their concerns to make the meeting safe. 

Margnialized groups are prioritized over those who aren't: privileged groups have the rest of the world to themselves, this is a space for the rest of us. A positive side effect it is creates a fun environment for cis white hetrosexual able men who like diversity and are good allies, but there's a difference between not enjoying yourself because there are no women/queers/etc in a space and not feeling safe in it.

**Comment by tef** [comment]
This is a writing guide, so i'm unsure it belongs in this issue.

**Comment by adacable** [comment]
Shall I open a separate issue, or put it in the "what is computer"?

**Comment by tef** [comment]
What is computer is perfect place, yep.
